<h1><center>Introductory Python for Data Science Notebook</center></h1>

<h1><center>Variables and Data Types</center></h1>
<h1><center>Introductory Data Structures</center></h1>
<h1><center>For Loops and While Loops</center></h1>
<h1><center>Functions</center></h1>
<h1><center>Basic Numpy and Pandas Operations</center></h1>
<h1><center>Basic Matplotlib Visualization</center></h1>

<h1><center>1.Variables and Data Types</center></h1>

## 1.1 Variables: 
##### you can think of variables as box containers that reserved memory locations to store values. This means that when you create a variable you reserve some space in memory.

## 1.2 Data Types:
##### in Python every value have a data type such as:

### Numbers:
##### There are two types of number:
##### integers: which are whole numbers
##### floating: which are numbers with decimal

### Strings: 
##### Strings are collections of letters or words In Python, you can create strings by enclosing single or double quotes

### Lists:
##### The list type is a container that holds bunch of objects in a given order and it also allows you to add and remove objects

### Tuples: 
##### A tuple is a sequence of immutable objects they are just like lists The differences between tuples and lists is, the tuples cannot be changed unlike lists and tuples use parentheses, whereas lists use square brackets.

### Dictionaries:
##### A dictionary in Python is an unordered collection of items that contain two element and they are keys and values 

### We created a program that calculate the sum of two number and we printed out the result using the print() function and of course we can apply that for multiplication and division and the subtraction

![title](../images/pic1.png)

### As we can can get the sum of two numbers we can do that for strings to

![title](../images/pic2.png)

<h1><center>2 Introductory Data Structures</center></h1>

## 2.1 Data structures: 
##### are fundamental concepts of computer science which helps in writing efficient programs in any language and it has a way of organizing and storing data sot hey can be accessed and worked with efficiently you'll learn about the various Python data structures and see how they are implemented

## 2.2 Various Python data structures :

### basic Data Structures:
#### this is some of the basic Data Structures objects

##### Integers
##### Float
##### Strings
##### Boolean

### advanced Data Structures:
#### this is a advanced Data Structures 

##### Arrays
##### Lists
##### Tuples
##### Dictionary
##### Sets

## Data Structures in a simple way

In [3]:
# Floats
x = 4.0
y = 2.0

# Addition
print (x + y)

# Subtraction
print (x - y)

# Multiplication
print (x * y)

# Division
print (x / y)

# Return the Reminder
print (x % y)

# return x the the power of y
print (x ** y)

# Return the Absolute value
print (abs(x))


6.0
2.0
8.0
2.0
0.0
16.0
4.0


## Advanced Data Structures

## Adding items to a list using .append() method

In [4]:
# List of numbers
list_ofnums = [1,2,3,4,5,6,7,8,9,10]

# Adding number 11 to the list
list_ofnums.append (11)
#Adding number The string 'am an item!!' to the list
list_ofnums.append ("am an item!!!")

#print out the list 
print (list_ofnums)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 'am an item!!!']


## Addition of strings

In [5]:
str1 = "I want to drink "
str2 = "Milk"

newstr = str1+str2

print (newstr)

I want to drink Milk


<h1><center>3 For Loops and While Loops</center></h1>

# 3.1 For Loop

### What is  a Loop?

##### Loops can execute a block of code number of times until a certain condition is met
# 3.2 What is For Loop?
##### For loop is used often when you have a piece of code which you want to repeat "n" number of time. 

##### In Python, for loops are called iterators Just like while loop, the for loop is also used to repeat the program But unlike while loop which depends on condition true or false. the For Loop uses the elements that it has to iterate

In [12]:
#How we use a for loop 
# the x is a varaible name you can name it how ever you wnat
for x in range(1,11):
    print (x)

1
2
3
4
5
6
7
8
9
10


## 3.3 What is While Loop?

##### While Loop is used to repeat a block of code It executes the code block multiple times Instead of running the code block once until a certain condition is met.

###### So now we know what is while loop now lets see how it works  here is a simple example of using a while loop

In [16]:
# Variable x
x = 0

# while x is less then 6 print x + 1
while (x < 6):
    x = x + 1
    print (x)

1
2
3
4
5
6


<h1><center>1 Python Functions</center></h1>

##### Functions are a convenient way to divide code into useful blocks and  make it more readable which only runs when it is called.You can pass data, known as parameters, into a function A function can return data as a result.

## 1.1 Creating a Function

#### In Python a function is defined using the def keyword inside the parentheses. You can add as many parameters as you want, just don't forget to separate them with a comma and An optional return statement to return a value from the function

## 1.2 Calling a Function

### To call a function, use the function name followed by its own parenthesis

## 1.3 The return statement

##### The return statement is used to exit a function and go back to where it was called.

In [21]:
# the function my_word have a parameter word inside of it 
def my_word(word = "hey"):
    # here we return the word
    return word
# simply call the function and print out the string 'hey'
my_word()

'hey'

<h1><center>Basic Numpy and Pandas Operations</center></h1>

# What is NumPy?:

##### NumPy is a Linear Algebra Library for Python it is one of the packages that you just can’t miss when you’re learning data science,this library provides you with an array data structure that holds some benefits over Python lists

### How to Use NumPy

##### numPy has many built-in functions we will focus on some of the most important once
##### Once you install NumPy let's import it as a library 

In [23]:
import numpy as npy

# Numpy Arrays

##### throughout the course we will be using arrays, it come in two flavors vectors and matrices 

##### we have 1d arrays and  2d matrices 

# Creating NumPy Arrays

## Note  We can create an array by directly converting a list

### 1dimensional array

In [25]:
mylist = [1,2,3,4,5] 

npy.array(mylist)

array([1, 2, 3, 4, 5])

### 2 dimensional matrices

In [27]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
npy.array(my_matrix)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

##### There are lots of built-in Methods

##### arange, zeros, ones, linspace, eye, random, reshape, max, min, argmax, argmin, shape, dtype

## arange

##### arange method is similar to a range method it just show numbers in  a specific range like the in given example

In [29]:
npy.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Zeros

#### Generate arrays of zeros

In [31]:
# 1 dimensional arrays
npy.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
# 2dimensional matrices
npy.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Ones

##### generatre arrays of ones

In [35]:
# 1 dimensional array
npy.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
# 2dimensional matrices
npy.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

##### linspace Return spaced numbers over a specified interval

In [45]:
npy.linspace(0,10,3)

array([ 0.,  5., 10.])

In [47]:
npy.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

## random

##### create random number arrays

### rand

##### Create an array of the given shape and populate it with random samples from a uniform distribution 0, 1

In [52]:
npy.random.rand(5)

array([0.97940914, 0.32108001, 0.83743152, 0.05970451, 0.51947388])

### randn

######  Return a samples from the a standard normal distribution

In [57]:
#1 dimensional array
npy.random.randn(2)

array([0.64232067, 0.72972278])

In [59]:
# 2 dimensional matrices
npy.random.randn(3,3)

array([[ 1.60245595, -0.94529002, -0.14594191],
       [ 0.02376959, -2.45799181, -0.07749712],
       [-0.34463631,  1.21901256, -0.38625426]])

### randint 

##### Return random integers from low value to high value

In [69]:
# return random single intger
npy.random.randint(1,100)

28

In [66]:
# return random intgers between 1 and 100 in step size of 10 numbers
npy.random.randint(1,100,10)

array([ 1, 57, 71, 56, 92, 56, 24, 49, 44, 90])

### max, min, argmax, argmin

##### this methods we use for finding max or min values. Or to find their index locations using argmin or argmax

In [83]:
myarray = npy.arange(30)

In [84]:
myarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [89]:
# return max value 
myarray.max()

29

In [90]:
#return max index of  value 
myarray.argmax()

29

In [91]:
# return min value 
myarray.min()

0

In [92]:
# return min index of  value 
myarray.argmin()

0

## reshape

##### Returns the same data with a new shape

In [95]:
# the new shape here is we have 3 columns and 10 rows
myarray.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

### dtype

##### we can also grab a data type of an object inside of  array

In [96]:
myarray.dtype

dtype('int32')